spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false   # El servidor no se registra a sí mismo
    fetch-registry: false         # No busca otros servicios
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0  # Arranca más rápido en desarrollo

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always